export default [
 {
    name: "Valentino Dress",
    season: "Summer",
    description: "Asymmetrical casual dress - White",
    img: "https://img01.ztat.net/article/spp-media-p1/38ad87710c1044d6b69c6319b177a7b5/8666a0a053044e1eb9eb4770598cf346.jpg?imwidth=300&filter=packshot",
    price: 495,
    gender: "women",
    category: "dresses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Valentino Dress",
    season: "Summer",
    description: "Asymmetrical casual dress - White",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQojOCLcMyUNB47CbnCQPiNU0pb9l1-wbFoZxX1odTvfby4yMwndOM5CzUMsfsQeJmJ-BA&usqp=CAU",
    price: 470,
    gender: "women",
    category: "dresses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Givenchy Dress",
    season: "All-season",
    description: "Satin gown dress - Gray",
    img: "https://cdn.rebelle.com//10/1096895120231128-1-1ej68cd.jpeg?width=500&height=500",
    price: 430,
    gender: "women",
    category: "dresses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Versace Dress",
    season: "Winter",
    description: "Versatile dress formal events - Skyblue",
    img: "https://cms.brnstc.de/product_images/680x930_retina/cpro/media/images/product/23/5/100146752317000_0_1683801104866.jpg",
    price: 175,
    gender: "women",
    category: "dresses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Chanel Dress",
    season: "Spring",
    description: "Vintage maxi dress - Black",
    img: "https://cdna.lystit.com/photos/farfetch/93d9ddf5/gucci-Black-Bib-collar-Velvet-Maxi-Dress.jpeg",
    price: 210,
    gender: "women",
    category: "dresses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Versace Dress",
    season: "Spring-Summer",
    description: "Ruffle-trimmed floral silk voile gown - Pink",
    img: "https://www.datocms-assets.com/59525/1681811428-1-252fe-252fe-252f5-252f1ee517759230456f5968ea26da9d3225ba5e6c06_xu80016296_1_fg.jpg?w=428&q=75&fit=crop&auto=format",
    price: 300,
    gender: "women",
    category: "dresses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Cecil",
    season: "Summer",
    description: "Lorena Vista leather jacket - Cream",
    img: "https://www.leathercompany.co.uk/images/ladies-leather-biker-jacket-beige-g-celia22-p7531-27307_thumb.jpg",
    price: 198,
    gender: "women",
    category: "Jackets",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Cecil",
    season: "Summer",
    description: "Lorena Vista leather jacket - Pink",
    img: "https://media.lloyd.com/rectangular-list-product-desktop-q90/F14-41021-OT_front_1.jpg",
    price: 198,
    gender: "women",
    category: "Jackets",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Cecil",
    season: "Summer",
    description: "Lorena Vista leather jacket - Pink",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMr614BUN5ukiZfnwfjwMh9_jKXmNmy63mSg&usqp=CAU",
    price: 198,
    gender: "women",
    category: "Jackets",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Cecil",
    season: "Summer",
    description: "Lorena Vista leather jacket - Pink",
    img: "https://m.media-amazon.com/images/I/61jklFoV5LL._AC_UF1000,1000_QL80_.jpg",
    price: 198,
    gender: "women",
    category: "Jackets",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Prada Jacket",
    season: "Spring",
    description: "Fitting jeans jacket - Black",
    img: "https://www.yoox.com/images/items/16/16298171nc_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
    price: 195,
    gender: "women",
    category: "Jackets",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Gucci",
    season: "Spring",
    description: "Distressed Jean Jacket - Black",
    img: "https://www.flannels.com/images/imgzoom/99/99090503_xxl.jpg",
    price: 200,
    gender: "women",
    category: "jackets",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Polo Jacket",
    season: "Winter",
    description: "winter jacket thermo-reflective lining - Blue",
    img: "https://i5.walmartimages.com/asr/26339861-dd29-41dd-9f81-82cc957d7a79.eb9ee9bce74db82999872c111bca3fa9.jpeg",
    price: 225,
    gender: "women",
    category: "jackets",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Balenciaga Coat",
    season: "Winter",
    description: "Fancy Dress coat - Beige",
    img: "https://www.alamodelabel.in/cdn/shop/files/DFA8FA80-D9E2-44FA-9C41-7D156E4EBD2F_600x.jpg?v=1702572594",
    price: 245,
    gender: "women",
    category: "jackets",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Balenciaga Coat",
    season: "Winter",
    description: "Fancy Dress coat - Red",
    img: "https://i5.walmartimages.com/asr/15c1a37e-66de-4f6e-af4b-1d344f7a8996.04d45331586464407342677af0c5b8b7.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
    price: 240,
    gender: "women",
    category: "jackets",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Dior Jacket",
    season: "Winter",
    description: "Denim winter jacket - Blue",
    img: "https://www.ubuy.co.de/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNzEwQXBmbCt5NkwuX0FDX1NMMTUwMF8uanBn.jpg",
    price: 310,
    gender: "women",
    category: "jackets",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Dockers Jacket",
    season: "All-season",
    description: "Sport jacket - Beige",
    img: "https://4.imimg.com/data4/RU/VC/MY-11853389/men-s-jackets.jpg",
    price: 175,
    gender: "man",
    category: "Jackets",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Dockers Jacket",
    season: "All-season",
    description: "Versatile sport jacket men - Jungle-Green",
    img: "https://i5.walmartimages.com/asr/e63c98cc-a04f-450c-960b-40b9de05023b.d3abf635d4da3677b680112b93507940.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
    price: 320,
    gender: "man",
    category: "jackets",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Oakley Men's Jacket",
    season: "Winter",
    description: "warm Winter Jacket - Snow-White",
    img: "https://cdna.lystit.com/520/650/n/photos/miinto/f1fd2b64/belstaff-white-Daunenjacke.jpeg",
    price: 390,
    gender: "man",
    category: "jackets",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Oakley jacket",
    season: "All-season",
    description: "Versatile winter jacket",
    img: "https://images.mtbiker.sk/eshop/big/216896-haglofs-bunda-haglofs-lim-mimic-hood-sedo-modra-4ca78785a4ba8ace82f52a6c4c3ed825.jpg",
    price: 345,
    gender: "man",
    category: "jacket",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Burberry Shirts",
    season: "All-season",
    description: "Classic, have enduring appeal and timeless style.",
    img: "https://assets.burberry.com/is/image/Burberryltd/73AC11F8-A46F-4CAC-8292-51ACA6A186E1?$BBY_V3_SL_1$&wid=1501&hei=1500",
    price: 200,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Tommy Hilfiger",
    season: "All-season",
    description: "Classic shirts, suitable for transitioning between seasons ",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS62Vp-a6m5pODbFCKYwSzG_N6LTRtCd_YfQ4Jo3v9alqdR6-uj3IxXEPU9hBEb7s49Pgc&usqp=CAU",
    price: 245,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Polo Shirts",
    season: "All-season",
    description: "Versatile, classic, men's shirt",
    img: "https://http2.mlstatic.com/D_NQ_NP_838158-MCO50534836593_062022-V.jpg",
    price: 259,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Burberry Select Shirt",
    season: "Winter",
    description: "Classic long sleeves cotton shirt",
    img: "https://media.sneakin.shop/catalog/product/cache/image/1800x/9df78eab33525d08d6e5fb8d27136e95/s/e/selected_16090424-4255235_1.jpg",
    price: 265,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Williot East",
    season: "All-season",
    description: "Regular fit men's shirt",
    img: "https://www.scheer-coaching.de/wp-content/uploads/2021/06/hemden-herren-orlebar-brown-giles-camisa-laurel.jpg",
    price: 180,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Williot East",
    season: "Spring",
    description: "Regular fit men's oriental shirt",
    img: "https://i.pinimg.com/736x/92/f2/bd/92f2bde753ffd1cde291fa08ba57b9a1.jpg",
    price: 220,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Williot East",
    season: "All-season",
    description: "Regular fit men's oriental shirt",
    img: "https://m.media-amazon.com/images/I/4126CL4SY7L._AC_UY1000_.jpg",
    price: 175,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Pier One",
    season: "Summer",
    description: "Basic plain regular fit trousers",
    img: "https://http2.mlstatic.com/D_NQ_NP_644834-MLM53445317170_012023-O.webp",
    price: 301,
    gender: "man",
    category: "trousers",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Pier One",
    season: "All-season",
    description: "Basic plain black slim fit trousers",
    img: "https://http2.mlstatic.com/D_NQ_NP_641920-MLM54825060888_042023-O.webp",
    price: 145,
    gender: "man",
    category: "trousers",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Tommy Hilfiger Chino",
    season: "Autumn",
    description: "Men regular fit cotton blend - Blue-Gold",
    img: "https://m.media-amazon.com/images/I/61ylk8E3sAL._AC_SX385_.jpg",
    price: 205,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Haunters",
    season: "Autumn",
    description: "Men regular fit cotton blend brown",
    img: "https://www.houseoffraser.co.uk/images/products/51451404_h.jpg",
    price: 210,
    gender: "man",
    category: "trousers",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Tommy Hilfiger Casual",
    season: "Autumn",
    description: "Men skinny fit trousers",
    img: "https://tiendaspillados.com/2917-large_default/pantalon-vestir-slim-cuadros-hombre.jpg",
    price: 350,
    gender: "man",
    category: "trousers",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Pier One",
    season: "All-season",
    description: "Men trousers regular fit cotton",
    img: "https://www.tesadisa.com/img/galeria/1681627552-0-0.webp",
    price: 270,
    gender: "man",
    category: "trousers",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Quiksilver",
    season: "All-season",
    description: "Basic black men's trousers",
    img: "https://http2.mlstatic.com/D_NQ_NP_743785-MLA40791076119_022020-O.webp",
    price: 320,
    gender: "man",
    category: "trousers",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Pier One",
    season: "Summer",
    description: "Basic cotton men's trousers",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJ9McG1eGj_U9BKP1_rqWjjU2vJdSoAjvacP9LdbFwKcYYN71hOseddRK5l5TXq87frQo&usqp=CAU",
    price: 149,
    gender: "man",
    category: "trousers",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Tommy Hilfiger",
    season: "All-seasons",
    description: "Basic cotton, regular fit men's trousers",
    img: "https://madmenmagazine.com/wp-content/uploads/2018/08/tiposdepantalonesdehombre.madmenmagazine1.jpg",
    price: 315,
    gender: "man",
    category: "trousers",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Prada",
    season: "Winter",
    description: "Brushed leather shoes, brown",
    img: "https://repunte.com/wp-content/uploads/2018/05/Botines.jpg",
    price: 660,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Michael Kors",
    season: "All-season",
    description: "Brushed leather shoes, black",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRg--elUgRmv2Qb26g7sh8e8mTOsmb3n-vW1ZFBWWvqDOULs8cd4-pXVx9Xon2s14iF20g&usqp=CAU",
    price: 580,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Gucci",
    season: "All-season",
    description: "Polished leather",
    img: "https://m.media-amazon.com/images/I/41MT3M7IjGL._AC_.jpg",
    price: 405,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Bugatti",
    season: "summer wear",
    description: "Smart zip-up-black",
    img: "https://i5.walmartimages.com.mx/mg/gm/3pp/asr/c0946199-f68f-489f-8f1f-71a400be291e.ca0f7b86125f3a1ae340b73c4dd04f34.jpeg?",
    price: 395,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Bugatti",
    season: "all year",
    description: "Lace-up ankle boots - brown",
    img: "https://img.kwcdn.com/product/Fancyalgo/VirtualModelMatting/28de4ff11bb30d82948dc679add89955.jpg?imageMogr2/auto-orient%7CimageView2/2/w/800/q/70/format/webp",
    price: 445,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Kazar",
    season: "all year",
    description: "Classic ankle boots - brown",
    img: "https://repunte.com/wp-content/uploads/2018/05/Botines.jpg",
    price: 445,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Lloyd",
    season: "all year",
    description: "Lace-up ankle boots - brown",
    img: "https://ae01.alicdn.com/kf/HTB1sZH4if2H8KJjy0Fcq6yDlFXaO.jpg_640x640Q90.jpg_.webp",
    price: 345,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Cecil",
    season: "Summer",
    description: "wrap skirt - pink",
    img: "https://p.globalsources.com/IMAGES/PDT/B1199028088/Damen-lange-Rocke.jpg",
    price: 245,
    gender: "women",
    category: "skirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Cecil",
    season: "Summer",
    description: "Pleated skirt - Pink",
    img: "https://vader-prod.s3.amazonaws.com/1678820848-falda-rosa-invitada-sfera-alta-costura-elle-3-6410c5ca1d145.png",
    price: 290,
    gender: "women",
    category: "skirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Mango",
    season: "all year",
    description: "Pleated skirt - darkpink",
    img: "https://ae01.alicdn.com/kf/Hbb3fb423236a418c952dca187b11d9ebK/Faldas-plisadas-Vintage-con-estampado-Floral-para-mujer-Falda-Midi-de-cintura-alta-de-algod-n.jpg",
    price: 356,
    gender: "women",
    category: "skirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Cecil",
    season: "spring",
    description: "Pleated Skirt - Darkblue",
    img: "https://m.media-amazon.com/images/I/51fbeCyixmL._AC_UY350_.jpg",
    price: 176,
    gender: "women",
    category: "skirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },

  {
    name: "Mango",
    season: "Summer",
    description: "Maxi- Skirt - Skyblue",
    img: "https://www.vila.com/on/demandware.static/-/Sites-pim-catalog/default/dwef251609/pim-static/VL/14082754/14082754_FederalBlue_001.jpg",
    price: 300,
    gender: "women",
    category: "skirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Mango",
    season: "all year",
    description: "Ruffle-trimmed floral silk voile gown",
    img: "https://i.pinimg.com/originals/2c/7b/10/2c7b109c707b21dea91fdb0d0be3a92b.jpg",
    price: 345,
    gender: "women",
    category: "skirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },

  {
    name: "Mango",
    season: "Summer",
    description: "Button and Laced Flirty Skirt - red",
    img: "https://i.pinimg.com/236x/7d/a1/48/7da148c50b58b2e1786d55483403cb70.jpg",
    price: 240,
    gender: "women",
    category: "skirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Mango",
    season: "all year",
    description: "Maxi-Skirt - Blue ",
    img: "https://img.bestdealplus.com/ae04/kf/H9e1c1800848d418ba3bca1819e56891bB.jpeg",
    price: 455,
    gender: "women",
    category: "skirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Mango",
    season: "all year",
    description: "Pleated Skirt - Green",
    img: "https://ae01.alicdn.com/kf/H82c8eb81c6894234a806b70f911e30d5P.jpeg_300x300Q70.jpeg_.webp",
    price: 145,
    gender: "women",
    category: "dresses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },

  {
    name: "Ray-Ban",
    season: "Summer",
    description: "Round sunglasses - black",
    img: "https://image4.cdnsbg.com/1/339/576441_1666860379034.jpg",
    price: 244,
    gender: "gifts",
    category: "jewelry",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "RayBan",
    season: "Summer",
    description: "Sunglasses- black and white",
    img: "https://www.sunniescr.com/cdn/shop/products/2840_b_1200x1200.jpg?v=1646793904",
    price: 345,
    gender: "gifts",
    category: "jewelry",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Burberry",
    season: "summer",
    description: "Sunglasses - black",
    img: "https://productosdelujo.cl/cdn/shop/products/CopiadeCopiadeCopiadeCopiadesky646454454-2021-10-23T103748.705_1200x.jpg?v=1634996296",
    price: 190,
    gender: "gifts",
    category: "jewelry",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Burberry",
    season: "Summer",
    description: "Sunglasses - tortoise shell",
    img: "https://www.visioncenter.com.pe/cdn/shop/products/7751000010010_1_e3a9e628-b708-42f2-a862-3fd0a843810f.jpg?v=1667904520",
    price: 165,
    gender: "gifts",
    category: "jewelry",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },

  {
    name: "Pilgrim",
    season: "Summer",
    description: "Sunglasses - black",
    img: "https://opticaval.es/wp-content/uploads/2023/03/190605402955.jpg",
    price: 170,
    gender: "gifts",
    category: "jewelry",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Michael Kors",
    season: "all year",
    description: "Trendy Leather Handbag - Green",
    img: "https://photos6.spartoo.de/photos/257/25755775/25755775_500_A.jpg",
    price: 301,
    gender: "gifts",
    category: "bags",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Michael Kors",
    season: "all year",
    description: "Crossbody Signiturebag - vanilla",
    img: "https://i.ebayimg.com/images/g/jbYAAOSwjrlkhxcO/s-l1200.webp",
    price: 198,
    gender: "gifts",
    category: "bags",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Michael Kors",
    season: "all year",
    description: "Trendy Leather Handbag - Orange",
    img: "https://img.giglio.com/images/prodZoom/E28479.004_1.jpg",
    price: 210,
    gender: "gifts",
    category: "bags",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Bruno Banani",
    season: "all year",
    description: "Trendy Leather Handbag - chocklate brown",
    img: "https://media.vogue.es/photos/5cc73acc92f81339724e5431/master/w_1600%2Cc_limit/voguees_moda_tendencias_470627995.jpg",
    price: 445,
    gender: "gifts",
    category: "bags",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Gucci",
    season: "summer ",
    description: "Trendy Leather Shoulder Bag - Pink",
    img: "https://www.cblbags.com/wp-content/uploads/2017/04/bolso-bandolera-gucci-soho-disco-piel-rosa-peonia-frontal-1.jpg",
    price: 245,
    gender: "gifts",
    category: "bags",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Bruno Banani",
    season: "all year",
    description: "Leather Wallet - darkbraun",
    img: "https://media.vogue.mx/photos/63698d1ca2b92778f422a4fa/master/w_1600%2Cc_limit/slide_6.jpg",
    price: 255,
    gender: "gifts",
    category: "wallets",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Bruno Banani ",
    season: "all year",
    description: "Leather Wallet - Braun",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVWwFqzbdhI-F53dWekjuZPc9XWNQj62aJHJGarluia9G-RvLjO6mUGZnX4Q4N_Jsl6ik&usqp=CAU",
    price: 645,
    gender: "gifts",
    category: "wallets",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Bruno Banani",
    season: "all year",
    description: "Leather Slim Wallet - Honeybraun",
    img: "https://latiendadelcuero.com/wp-content/uploads/2019/12/1910-Cartera-cuero-hombre.jpg",
    price: 119,
    gender: "gifts",
    category: "wallets",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Scarfs 4 You",
    season: "Winter",
    description: "Checked Scarf - Red",
    img: "https://www.fourruresgrenier.ca/wp-content/uploads/4981-Rus.jpg",
    price: 365,
    gender: "gifts",
    category: "jewelry",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Scarfs 4 You",
    season: "winter",
    description: "Checked Scarf - Darkblue",
    img: "https://www.thedealoutlet.com/dw/image/v2/BGBX_PRD/on/demandware.static/-/Sites-thedealoutlet-master-catalog/default/dw8506f4cf/025926113433_1.jpg?sw=669&sh=1124",
    price: 176,
    gender: "gifts",
    category: "jewelry",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Scarfs 4 You",
    season: "all year",
    description: "Cotton Checked Pattern - Red",
    img: "https://i.ebayimg.com/images/g/gy8AAOSwjLFjT1g2/s-l1600.jpg",
    price: 300,
    gender: "gifts",
    category: "jewelry",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Scarfs 4 You",
    season: "winter",
    description: " Cotton Checked Pattern - Beige",
    img: "https://statics-cdn-v2.fashionette.net/transform/63e23fc4-e602-4489-bb4f-789f33a797cc/A0192302_Burberry_position_1?io=transform:extend,width:728,height:728,background:white&quality=100",
    price: 145,
    gender: "gifts",
    category: "jewelry",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Next",
    season: "Spring",
    description: "Long Sleeve Chiffon Blouse - purple ",
    img: "https://ae01.alicdn.com/kf/S06eed8ec5cee43258aca3d0912ee5f12p.jpg_640x640Q90.jpg_.webp",
    price: 215,
    gender: "women",
    category: "blouses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Vero Moda",
    season: "Summer",
    description: "Short Sleeve V-Neck - Beige ",
    img: "https://arturocalle.vtexassets.com/arquivos/ids/553202/MUJER-BLUSA-10131216-HABANO-320_1.jpg?v=638193530571700000?1700870400015",
    price: 245,
    gender: "women",
    category: "blouses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Alan Paine",
    season: "all year",
    description: "",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPyPgygu68HojWcYLJhPgFd3ak8D5QpfVUjkLUjWLRfgcUM74NzhhfvuiX-PvSikUft10&usqp=CAU",
    price: 199,
    gender: "women",
    category: "blouses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Next",
    season: "all year",
    description: "charcoal balck beautiful blouse",
    img: "https://img.mytheresa.com/332/376/90/jpeg/catalog/product/6f/P00867309.jpg",
    price: 245,
    gender: "women",
    category: "blouses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Next",
    season: "summer",
    description: "woolen crop top - pink",
    img: "https://cdn-images.farfetch-contents.com/21/54/71/63/21547163_51782222_300.jpg",
    price: 119,
    gender: "women",
    category: "blouses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Orange",
    season: "Summer",
    description: "Long sleeve with buttons - Peach",
    img: "https://cdn-images.farfetch-contents.com/20/19/13/52/20191352_50228746_300.jpg",
    price: 565,
    gender: "women",
    category: "blouses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Orange",
    season: "all year",
    description: "Long Sleeve Blouse With Ruffles - white  ",
    img: "https://www.yoox.com/images/items/10/10183480LJ_14_f.jpg?impolicy=crop&width=387&height=490",
    price: 176,
    gender: "women",
    category: "blouses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Orange",
    season: "winter",
    description: "Long Sleeve blouse - Black and White",
    img: "https://b2c-media.maxmara.com/sys-master/m0/MM/2023/2/1196023306/008/s3details/1196023306008-y-curacao_thumbnail.jpg",
    price: 301,
    gender: "women",
    category: "blouses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Orange",
    season: "Winter",
    description: "pullneck Long Sleeve - black and white",
    img: "https://images.fashiola.es/product-list/300x450/amazon/616011755/vmsaba-ls-blouse-girl-sueter-116-cm-para-ninas.webp",
    price: 450,
    gender: "women",
    category: "blouses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Orange",
    season: "Summer",
    description: "Long Sleeve blouse - Cream",
    img: "https://images.fashiola.mx/product-list/300x450/italist/574300517/blousa.webp",
    price: 460,
    gender: "women",
    category: "blouses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Orange",
    season: "summer",
    description: "Short Sleeve blouse - white ",
    img: "https://la.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-blusa-con-volantes-destacados--FHBL13AQV000_PM2_Front%20view.jpg",
    price: 245,
    gender: "women",
    category: "blouses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Nenette",
    season: "summer",
    description: "Draped evening dress - Olive",
    img: "https://data.mascheronistore.com/imgprodotto/abito-d-drappeggiato-nenette_122921_zoom.jpg",
    price: 345,
    gender: "women",
    category: "dresses",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Jack & Jones",
    season: "all year",
    description: "Comfort Fit Shirt - White/Navy",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9WiLLL6C2GZpFchbLnqrDxaeCI1h8OV_Jfw&usqp=CAU",
    price: 436,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Jack & Jones",
    season: "all year",
    description: "Casual Shirt - Black/Red",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIc1BLILlnru_VA1RsnV3miuphnZviu8K_1w&usqp=CAU",
    price: 437,
    gender: "man",
    category: "shirts",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Jack & Jones",
    season: "summer",
    description: "Casual Shirt - Blue",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvxYKVUSVdzxRyLfIwyPUd6OB3Z3zjg5gnk2ZGRlhqwyhB09f76ye-0ytoMObg8Jm8Ag8&usqp=CAU",
    price: 438,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Jack & Jones",
    season: "all year",
    description: "Casual Shirt - Grey",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4pDjODC_ymtJ1bPNyztJFdyvPQPk2g2Rabw&usqp=CAU",
    price: 439,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Pier One",
    season: "all year",
    description: "Denim Shirt - Blue",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_riBXF3gBpY6zVGOcm4F_h-8GjGWyAuRmAA&usqp=CAU",
    price: 440,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Pier One",
    season: "Summer",
    description: "Casual Fit Shortsleeve - Green/Grey",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrT-oRNUjwnN6LCndRtqzu6lafJCVy-_DLeQ&usqp=CAU",
    price: 441,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Jack & Jones",
    season: "all year",
    description: "Casual Fit Shortsleeve - Blue",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZ9JwoxCjmjyiM14KDGTilI5_5BARWTJvQ0Q&usqp=CAU",
    price: 442,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Jack & Jones",
    season: "Summer",
    description: "Slim Fit Longsleeve - Darkblue",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWklp20htNjWvipfrUZpArPkQOZ3i2x9aurRN8ajV5sRl_j6oXuQrIyWnmOZIqrAYQmsY&usqp=CAU",
    price: 443,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Jack & Jones",
    season: "Summer",
    description: "Slim Fit Longsleeve - Grey/White",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVZxtNPdkjYU1ptHboGpBZB_m8iAyY6NlzCA&usqp=CAU",
    price: 444,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Jack & Jones",
    season: "Summer",
    description: "Slim Fit Longsleeve - Grey/Blue",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuBTp_IvRBGsy9POWcw8zBa-CWEdxDkYTNtw&usqp=CAU",
    price: 445,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Lee",
    season: "Summer",
    description: "Slim Fit Longsleeve - Grey/White",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDMeQia3eGEfDiCSkcGeKhutdYWfprP28bxA&usqp=CAU",
    price: 246,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Fossil",
    season: "Leather Wallet - Green",
    description: "",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEYjkzrfGFOw-m9jGborr3e0z0MhuEfcFzBvI0xQYT7GyhUUEZj5DncDFABClYtt3gEkw&usqp=CAU",
    price: 447,
    gender: "gifts",
    category: "jewelry",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Jack & Jones",
    season: "summer",
    description: "Slim Fit Longsleeve Shirt - Mint-green",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4LXYNJzRzvu0UTKPxeIiFi64c_RDHLHO25Q&usqp=CAU",
    price: 448,
    gender: "man",
    category: "shirts",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Bugatti",
    season: "all year",
    description: "Official Leather Shoes - brown",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8RKYPb8MrJkn79OmpuQT-vdj-Kt1m7WOzdQ&usqp=CAU",
    price: 565,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Bugatti",
    season: "Summer",
    description: "Casual Leather Shoes - Brown",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXXq7OXN5pdKxku-pZo4Qf1VsTX1zmcIMEBg&usqp=CAU",
    price: 760,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Lloyd",
    season: "all year",
    description: "Official Leather Shoes - Brown",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCUhB-4c2vIuiNmjajvtCF7-UWko2n7w5jew&usqp=CAU",
    price: 310,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "95",
    season: "all year",
    description: "Official Leather Shoes - Black",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-O1K2TqT0WMB2JoAtLDIXXM9qz_pysRkPnw&usqp=CAU",
    price: 345,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Gucci",
    season: "all year",
    description: "Official Leather Shoes - Brown",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTADqPlbHMtCTl9MUGpLEu4vxT57HdjvZw1Q&usqp=CAU",
    price: 345,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Michael Kors",
    season: "all year",
    description: "Official Leather Boots - Black",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXR0iXMHrODvTFNURibGOvtKSuUiGJTWeEaA&usqp=CAU",
    price: 244,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Michael Kors",
    season: "all year",
    description: "Official Leather Shoes - Brown",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiTu1dnjgpFXM_WcMR0QX9dddc0KCH18nMrw&usqp=CAU",
    price: 245,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Prada",
    season: "all year",
    description: "Zipup Official Leather Boots - Brown",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDcNd64rBNgS34S8rsTrEwESEXc4EByPcnww&usqp=CAU",
    price: 445,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Gucci",
    season: "all year",
    description: "Official Leather Ankleboots - HoneyBrown",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGXqDSWp-0T90Ue0-V2twtOPVW_Co1E4FWuA&usqp=CAU",
    price: 244,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Prada",
    season: "summer",
    description: "Official Leather Ankleboots - HoneyBrown",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwNNfR3iabavmF9lLgXUCbU2ZvyBpBs0FeWA&usqp=CAU",
    price: 119,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Prada",
    season: "Spring",
    description: "Fancy Leather Boots - brown",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1vQkT-KlyKEghYPSCZt0gSnZnW1_X2duCug&usqp=CAU",
    price: 565,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Lloyd",
    season: "Spring/Autom",
    description: "Casual Leather Boots - Black",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3yIsUrg7XHgiZuEe1f5mML-eIsLbwPa3sGRbEatvdtfSYkhJwJa5ibCOO7TuvDtBaFfg&usqp=CAU",
    price: 176,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Kazar",
    season: "all year",
    description: "Zipp up Fancy Ankleboots - Red",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9AhcCQapZ4M08x2gSzdtLBws0AlyhsbsPnQ&usqp=CAU",
    price: 301,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Michael Kors",
    season: "Summer",
    description: "Elegant Leather Shoes with laces - White",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhhgJmtKRH1BUIAZiIDjAkhbMOMWN2sMn83g&usqp=CAU",
    price: 345,
    gender: "man",
    category: "shoes",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Nura",
    season: "all year",
    description: "A close up Bracelet with diamonds",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFjaygwSZnTmRUFxGcbu72Jb7YW7RLGHRHkg&usqp=CAU",
    price: 335,
    gender: "gifts",
    category: "jewelry",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Nura",
    season: "all year",
    description: "Crystal Clear Diamonds necklace - white ",
    img: "https://bright-river.com/wp-content/uploads/2022/10/background-for-jewelry-photography-copy.webp",
    price: 330,
    gender: "gifts",
    category: "jewelry",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Nura",
    season: "all year",
    description: "Beautiful Silver Colored Bracelets - Silver",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQy-Wb1yf_PAWriDWGy0zSyea_1mTzlWcXI3g&usqp=CAU",
    price: 245,
    gender: "gifts",
    category: "jewelry",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Nura",
    season: "all year",
    description: "World necklace - Gold",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpIp7-ey7rbNxOfFx-cntsDuAth6r1yJxN7w&usqp=CAU",
    price: 244,
    gender: "gifts",
    category: "jewelry",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Nura",
    season: "all year",
    description: "Lavish Diamond Necklace - White/Gold",
    img: "https://danibydk.com/cdn/shop/files/GLDN003WHW0000.jpg?v=1700749403&width=2048",
    price: 245,
    gender: "gifts",
    category: "jewelry",
    sizes: [],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Pier One",
    season: "winter",
    description: "Bomber Jacket - light and dark Blue",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNZzO9ZcaAx_g1FT_UGBzm2C789DvDN36NZw&usqp=CAU",
    price: 175,
    gender: "man",
    category: "jackets",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Pier One",
    season: "winter",
    description: "Bomber Jacket - charcoal black",
    img: "https://cdn.aboutstatic.com/file/images/15774e901ef3db57f044320f659bceca.png?bg=F4F4F5&quality=75&trim=1&height=480&width=360",
    price: 165,
    gender: "man",
    category: "jackets",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
  {
    name: "Pier One",
    season: "winter",
    description: "Bomber Jacket - Jungle-Green",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSX1F1KRzefGuJr0AqWBvh0J5rZgBTG9m8xHA&usqp=CAU",
    price: 195,
    gender: "man",
    category: "jackets",
    sizes: [36, 38, 42, 44, 46],
    size: [],
    rating: {
      rate: 5,
      count: 5,
    },
  },
];

